# Generated by Django 5.0.2 on 2025-09-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="Ramza's Chillas", help_text='Restaurant name displayed on site', max_length=100)),
                ('site_description', models.TextField(default='Chill Vibes • Hot Food', help_text='Tagline for your restaurant')),
                ('phone_number', models.CharField(default='(555) 123-CHILL', help_text='Restaurant phone number', max_length=20)),
                ('email', models.EmailField(default='hello@ramzaschillas.com', help_text='Restaurant email', max_length=254)),
                ('address', models.TextField(default='123 Chill Street, Island City', help_text='Restaurant address')),
                ('opening_time', models.TimeField(default='09:00', help_text='Daily opening time')),
                ('closing_time', models.TimeField(default='22:00', help_text='Daily closing time')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=3.99, help_text='Standard delivery fee', max_digits=6)),
                ('free_delivery_minimum', models.DecimalField(decimal_places=2, default=25.0, help_text='Minimum order for free delivery', max_digits=8)),
                ('delivery_radius', models.IntegerField(default=5, help_text='Delivery radius in kilometers')),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0825, help_text='Tax rate (e.g., 0.0825 for 8.25%)', max_digits=5)),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image (recommended: 1200x800px)', null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, help_text='Restaurant logo (recommended: 200x200px)', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(blank=True, help_text='Calories per serving (optional)', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Alert when stock falls below this number'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.IntegerField(default=100, help_text='Current stock level (0 = out of stock)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of this category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Category display image (recommended: 400x300px)', null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Show this category on the menu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Category name (e.g., Burgers, Pizzas)', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Lower numbers appear first'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(help_text='Which category this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant.category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(help_text='Detailed description for customers'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Food photo (recommended: 600x400px)', null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Show this item on the menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage as featured item'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(help_text='Item name as it appears on the menu', max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='preparation_time',
            field=models.IntegerField(default=15, help_text='Preparation time in minutes'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in dollars (e.g., 12.99)', max_digits=8),
        ),
    ]
