# Generated by Django 5.0.2 on 2025-09-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_sitesettings_menuitem_calories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home_hero', 'Home - Hero Section'), ('home_features', 'Home - Features Section'), ('home_cta', 'Home - Call to Action'), ('menu_hero', 'Menu - Hero Section'), ('footer', 'Footer Content'), ('navigation', 'Navigation'), ('about', 'About Page'), ('contact', 'Contact Page'), ('checkout', 'Checkout Page'), ('cart', 'Cart Page')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, help_text='Main heading/title', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Subtitle or tagline', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Main content/description')),
                ('button_text', models.CharField(blank=True, help_text='Button text if applicable', max_length=100)),
                ('button_url', models.CharField(blank=True, help_text='Button URL if applicable', max_length=200)),
                ('extra_text_1', models.TextField(blank=True, help_text='Additional text field 1')),
                ('extra_text_2', models.TextField(blank=True, help_text='Additional text field 2')),
                ('extra_text_3', models.TextField(blank=True, help_text='Additional text field 3')),
                ('image', models.ImageField(blank=True, help_text='Main image for this section', null=True, upload_to='content/')),
                ('background_image', models.ImageField(blank=True, help_text='Background image', null=True, upload_to='content/backgrounds/')),
                ('meta_title', models.CharField(blank=True, help_text='Page title for SEO', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='Page description for SEO')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Section',
                'verbose_name_plural': 'Content Sections',
                'ordering': ['section'],
            },
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='hero_image',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_text',
            field=models.TextField(default='Mon-Thu: 11:00 AM - 10:00 PM\nFri-Sat: 11:00 AM - 11:00 PM\nSunday: 12:00 PM - 9:00 PM', help_text='Detailed business hours display'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_time_text',
            field=models.CharField(default='25-30 minutes', help_text='Expected delivery time', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon (recommended: 32x32px)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(default="© 2024 Ramza's Chillas. All rights reserved.", help_text='Copyright text', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_description',
            field=models.TextField(default='Serving the finest food with fresh ingredients and chill vibes since 2024. Your go-to spot for quality meals in a relaxed atmosphere.', help_text='Footer description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_about_text',
            field=models.CharField(default='About', help_text='About navigation text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_cart_text',
            field=models.CharField(default='Cart', help_text='Cart navigation text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_contact_text',
            field=models.CharField(default='Contact', help_text='Contact navigation text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_home_text',
            field=models.CharField(default='Home', help_text='Home navigation text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='nav_menu_text',
            field=models.CharField(default='Menu', help_text='Menu navigation text', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter page URL'),
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this image', max_length=200)),
                ('image_type', models.CharField(choices=[('logo', 'Logo'), ('hero', 'Hero Images'), ('background', 'Background Images'), ('category', 'Category Images'), ('menu_item', 'Menu Item Images'), ('gallery', 'Gallery Images'), ('icon', 'Icons'), ('other', 'Other Images')], default='other', max_length=20)),
                ('image', models.ImageField(help_text='Upload image file', upload_to='site_images/')),
                ('alt_text', models.CharField(help_text='Alt text for accessibility', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the image')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_in_sections', models.ManyToManyField(blank=True, help_text='Which content sections use this image', to='restaurant.contentsection')),
            ],
            options={
                'verbose_name': 'Site Image',
                'verbose_name_plural': 'Site Images',
                'ordering': ['image_type', 'sort_order', 'name'],
            },
        ),
    ]
