# Generated by Django 5.0.2 on 2025-09-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_contentsection_remove_sitesettings_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in Rand (e.g., 12.99)', max_digits=8),
        ),
    ]
