# Generated by Django 5.0.2 on 2025-11-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=100)),
                ('customer_title', models.CharField(blank=True, help_text="Customer's title or role (optional)", max_length=100)),
                ('review', models.TextField(help_text="Customer's review")),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('image', models.ImageField(blank=True, help_text='Customer photo (optional)', null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on the website')),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['sort_order', 'customer_name'],
            },
        ),
    ]
