services:
  - type: web
    name: RamzaKitchen
    env: python
    buildCommand: "pip install -r requirements.txt && python build_frontend.py && python manage.py collectstatic --noinput"
    startCommand: "python start_server.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4
      - key: CSRF_TRUSTED_ORIGINS
        value: https://ramzas-chillas.onrender.com,https://ramza-ut50.onrender.com,https://ramzakitchen.onrender.com,https://ramzas-chillas.site