services:
  - type: web
    name: RamzaKitchen
    env: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .. && python manage.py collectstatic --noinput"
    startCommand: "python start_server.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 4